### ISSUE TITLE
Datasets availability 

### ISSUE THREAD

**Issue by eebowen** [Alexandre-Delplanque/HerdNet#2]
Hello, 
Thank you for your great work! Are the two datasets (Ennedi 2019 and Delplanque et al. 2022) you mentioned in this repo available to download?  If so, how to download them? Thanks.

**Comment by Alexandre-Delplanque** [comment]
Hi @eebowen,
Thanks! Unfortunately, the Ennedi dataset can not be shared, but you can find and use the HerdNet's trained parameters in the README, the dataset of Delplanque et al. (2022) will soon be available again (we're migrating the dataset to another server).
I'll post the new link here and in the README once completed.
Thanks for waiting.
Best.

**Comment by Alexandre-Delplanque** [comment]
Hi @eebowen,
Here is the new link to the dataset: https://doi.org/10.58119/ULG/MIRUU5
Have fun!
