### ISSUE TITLE
The issue about how to draw prediction points in the raw pic 

### ISSUE THREAD

**Issue by xiaotongtongxue** [Alexandre-Delplanque/HerdNet#6]
Hi! @Alexandre-Delplanque , I'm coming again. When I run the Evaluator class in the evaluators.py, I find the `vizual_fn` is always None, and I don't see any function to call from this project. Could you help me solve this problem? Thanks!

**Comment by Alexandre-Delplanque** [comment]
Hi @xiaotongtongxue,

Sure! First, as stated in the Evaluator's docstring ([here](https://github.com/Alexandre-Delplanque/HerdNet/blob/6c9f9004c18d8f29ca19e0784ee31e564024770e/animaloc/eval/evaluators.py#L75)), the `vizual_fn` arg should be used when you're working with [Wandb](https://wandb.ai/). It is a simple function used to plot some samples during validation/testing. Unfortunately, I haven't provided an example function in the project, but I have given some hints on how to write one in the docstring.

Hope this helps!
